# to set up 'kube-master' nodes
- hosts: kube-master
  roles:
  - kube-master
  - kube-node
  tasks:
  - name: Setting master role name 
    shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
    ignore_errors: true
    delegate_to: "{{ groups.deploy[0] }}"

  - name: Making master nodes NoSchedule
    shell: "{{ bin_dir }}/kubectl taint node {{ inventory_hostname }} kubernetes.io/role=master:NoSchedule  --overwrite"
    delegate_to: "{{ groups.deploy[0] }}"
    when: DEPLOY_MODE != "allinone"
    ignore_errors: true
