# WARNING: Upgrade the k8s cluster can be risky. Make sure you know what you are doing.
# Read the guide: 'op/upgrade.md' .

# update kubectl binary
- hosts:
  - kube-master
  - kube-node
  - deploy
  roles:
  - prepare

# update masters
- hosts: 
  - kube-master
  roles:
  - kube-node
  - kube-master
  tasks:
  - name: Setting master role name 
    shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
    ignore_errors: true
    delegate_to: "{{ groups.deploy[0] }}"

# update nodes
- hosts: 
  - kube-node
  roles:
  - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }
