# dns 自动安装，可选"coredns"和“kubedns”
dns_install: "yes"
dns_backend: "coredns"
kubednsVer: "1.14.13"
corednsVer: "1.5.0"
kubedns_offline: "kubedns_{{ kubednsVer }}.tar"
coredns_offline: "coredns_{{ corednsVer }}.tar"
dns_offline: "{%- if dns_backend == 'coredns' -%} \
                {{ coredns_offline }} \
              {%- else -%} \
                {{ kubedns_offline }} \
              {%- endif -%}"

# metric server 自动安装
metricsserver_install: "yes"
metricsVer: "v0.3.2"
metricsserver_offline: "metrics-server_{{ metricsVer }}.tar"

# dashboard 自动安装
# 现阶段 dashboard 获取metrics仍旧依赖于heapster，因此需连带安装heapster
dashboard_install: "yes"
dashboardVer: "v1.10.1"
dashboard_offline: "dashboard_{{ dashboardVer }}.tar"
heapsterVer: "v1.5.4"
heapster_offline: "heapster_{{ heapsterVer }}.tar"

# ingress 自动安装，可选 "traefik" 和 "nginx-ingress"
ingress_install: "yes"
ingress_backend: "traefik"
traefikVer: "v1.7.12"
nginxingVer: "0.21.0"
traefik_offline: "traefik_{{ traefikVer }}.tar"
nginx_ingress_offline: "nginx_ingress_{{ nginxingVer }}.tar"
traefik_ui_domain: "traefik-k8s1-dev.xxx.com"

# metallb 自动安装
metallb_install: "no"
metallbVer: "v0.7.3"
# 模式选择: 二层 "layer2" 或者三层 "bgp"
metallb_protocol: "layer2"
metallb_offline: "metallb_{{ metallbVer }}.tar"
metallb_vip_pool: "192.168.1.240/29"


# fluentd 自动安装
fluentd_install: "yes"
fluentd_offline: "fluentd_v1.2.5-kafka-0.9.tar"
fluentd_es_server: "172.21.246.100:9200,172.21.249.34:9200"
fluentd_kafka_brokers: "10.12.0.26:9092"
fluentd_kafka_topic: "dubbo_chain_log"

# 是否安装自定义的相关组件
private_install: "yes"