# dns 自动安装，可选"coredns"和“kubedns”
dns_install: "yes"
dns_backend: "coredns"
kubedns_offline: "kubedns_1.14.13.tar"
coredns_offline: "coredns_1.2.2.tar"
dns_offline: "{%- if dns_backend == 'coredns' -%} \
                {{ coredns_offline }} \
              {%- else -%} \
                {{ kubedns_offline }} \
              {%- endif -%}"

# metric server 自动安装
metricsserver_install: "yes"
metricsserver_offline: "metrics-server_v0.3.1.tar"

# dashboard 自动安装
dashboard_install: "yes"
dashboard_domain: "dashboard-k8s1-dev.xxx.com "
dashboard_offline: "dashboard_v1.10.0.tar"

# traefik-ingress 自动安装
ingress_install: "yes"
ingress_backend: "traefik"
traefik_offline: "traefik_v1.7.2.tar"
traefik_ui_domain: "traefik-k8s1-dev.xxx.com"

# fluentd 自动安装
fluentd_install: "yes"
fluentd_offline: "fluentd_v1.2.5-kafka-0.9.tar"
fluentd_es_server: "172.21.246.100:9200,172.21.249.34:9200"
fluentd_kafka_brokers: "10.12.0.26:9092"
fluentd_kafka_topic: "dubbo_chain_log"

# heapster 自动安装
heapster_install: "yes"
heapster_offline: "heapster_v1.5.4.tar"

# efk 自动安装
#efk_install: "no"

# prometheus 自动安装
#prometheus_install: "no"
