alertmanager:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 39001

server:
  persistentVolume:
    enabled: false
  service:
    type: NodePort
    nodePort: 39000

pushgateway:
  enabled: false

kubeStateMetrics:
  image:
    repository: ccr.ccs.tencentyun.com/weimob-k8s-google-containers/kube-state-metrics:v1.3.1
