- block:
    - block:
      - name: 尝试推送离线fluentd镜像（若执行失败，可忽略）
        copy: src={{ base_dir }}/down/{{ fluentd_offline }} dest=/opt/kube/images/{{ fluentd_offline }}
        when: 'fluentd_offline in download_info.stdout'

      - name: 获取fluentd离线镜像推送情况
        command: "ls /opt/kube/images"
        register: image_info

      - name: 导入fluentd的离线镜像（若执行失败，可忽略）
        shell: "{{ bin_dir }}/docker load -i /opt/kube/images/{{ fluentd_offline }}"
        when: 'fluentd_offline in image_info.stdout'

      - name: 在deploy 节点创建相关目录
        file: path={{ item }} state=directory
        with_items:
        - /opt/kube/kube-system/fluentd
        delegate_to: "{{ groups.deploy[0] }}"

      - name: 准备fluentd的部署文件
        template: src={{ item }}.yaml.j2 dest=/opt/kube/kube-system/fluentd/{{ item }}.yaml
        with_items:
        - fluentd-configmap
        - fluentd-ds
        delegate_to: "{{ groups.deploy[0] }}"

      - name: 创建fluentd部署
        shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/fluentd/"
        delegate_to: "{{ groups.deploy[0] }}"
        run_once: true