# 默认使用kube-proxy的 'iptables' 模式，可选 'ipvs' 模式(experimental)
PROXY_MODE: "iptables"

# Kubelet 根目录
KUBELET_ROOT_DIR: "{{ data_dir }}/kubelet"

# node节点最大pod 数
MAX_PODS: 188

#是否开启绑核
KUBE_BIND_CPU_ENABLED: "yes"
