# 默认使用kube-proxy的 'iptables' 模式，可选 'ipvs' 模式(experimental)
PROXY_MODE: "iptables"

# 基础容器镜像
SANDBOX_IMAGE: "ccr.ccs.tencentyun.com/weimob-k8s-google-containers/pause-amd64:3.1"
#SANDBOX_IMAGE: "registry.access.redhat.com/rhel7/pod-infrastructure:latest"

# Kubelet 根目录
KUBELET_ROOT_DIR: "{{ data_dir }}/kubelet"

# node节点最大pod 数
MAX_PODS: 125

# 配置为kube组件（kubelet,kube-proxy,dockerd等）预留的资源量
KUBE_RESERVED_ENABLED: "no"
KUBE_RESERVED: "cpu=200m,memory=1Gi,ephemeral-storage=1Gi"
SYS_RESERVED: "cpu=200m,memory=1Gi,ephemeral-storage=1Gi"

# 配置kubelet的hard eviction条件
HARD_EVICTION: "memory.available<1Gi,nodefs.available<10%"

# 配置kubelet绑核
KUBE_BIND_CPU_ENABLED: "yes"
